services:
  product-service:
    build:
      context: ./product-service/
      # target: final
    ports:
      - 9000:5193
    links:
      - product-postgres-db
      - service-discovery
    environment:
      - ConnectionStrings__ProductServiceConnection=Host=product-postgres-db;Port=8000;Database=ProductDb;Username=postgres;Password=password123
      - ConsulConfiguration__Host=http://service-discovery:8500
      - ServiceConfiguration__Host=product-service
      - ServiceConfiguration__Port=5193
      - ServiceConfiguration__ServiceName=Product-Service
    depends_on:
      product-postgres-db:
        condition: service_healthy
      service-discovery:
        condition: service_started
    networks:
      - dev
  product-postgres-db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-product-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 8000:5432
    networks:
      - dev
  identity-service:
    build:
      context: ./identity-service/
      # target: final
    ports:
      - 9001:5217
    links:
      - identity-postgres-db
      - service-discovery
    environment:
      - ConnectionStrings__ProductServiceConnection=Host=identity-postgres-db;Port=8001;Database=ProductDb;Username=postgres;Password=password123
      - ConsulConfiguration__Host=http://service-discovery:8500
      - ServiceConfiguration__Host=identity-service
      - ServiceConfiguration__Port=5217
      - ServiceConfiguration__ServiceName=Identity-Service
    depends_on:
      identity-postgres-db:
        condition: service_healthy
      service-discovery:
        condition: service_started
    networks:
      - dev
  identity-postgres-db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-identity-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 8001:5432
    networks:
      - dev
  service-discovery:
    image: consul:1.15.4
    ports:
      - 8500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - dev
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - dev

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    networks:
      - dev
volumes:
  db-product-data:
  db-identity-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  dev:
    driver: bridge
